language: node_js

node_js:
  - 6
  - 7
  - 8

services:
  - mongodb

install:
  - yarn

cache:
  yarn: true
  directories:
  - node_modules

script:
  - yarn build

deploy:
  - provider: heroku
    skip_cleanup: true
    app: glab-staging-reader-api
    on:
      branch: master
      node: '8'
  - provider: heroku
    skip_cleanup: true
    app: glab-reader-api
    on:
      tags: true
      node: '8'

notifications:
  email: false
  slack:
    secure: vx2lx814br9ZtInNa13mff1ohrz1rb935dK55FZxelV9ebqCESyfd66q6u9iijGwALDJXVCbhs3TctVI+Gmvu3U7gaRxtLHjErgXsJVdEXb6ya0J6cTrrVEi/V0Euq87kbX1Qd8RvnCZO5YQLn2oG/517Ywu2IaIE7YkPpWKOJqn/DprqoZ1F6s+0Lhrnvx2IaS2qXRMl1yK8DhdmKuY2FqkCQibUjCJGcZvY6/PYVS95TPCuQLefu6SJn0lnsKI4M0YBhOa4kMFxTX31aoSGhX1AyCoEJwJSs/FCHRY8UsvccQYtXNiaiHz+IJp85m1O1jCm2Dn+xgwNETi8hQxjB1zYIduCk5OEk1GxMaPgip8/5WLNc7kl9wi6Kyt92SyLScrJQ0I9vD8KcJy2YQxjYtqiD/opFiSWQPXMwqa+Ngl0EdpTez55fqDMehyuV+GWngjhx4hE4fDAZlvGRjNPNBlS43Y4usgEDDtaqbQNPmJnSZtonyNluoq7M+UlZAJq+6q/V6Mb6qzGvsLFe1P1VtPygeFuRN28Dp3/ZH+aP4Itooy86OfidthBRnkxo9DGO7OvpcNNBVuPbJhQadMljTH7Lc9Y/UvwK4R4HXdFvN7jcPRkeP2aOh1m2fc2uFUsW7UTu3zo0YiX7Z3P//eAWoFMldFsCKsIPMMvBf5I8U=
