sudo: required

language: node_js

node_js:
- 9

env:
- DOCKER_REPO=gorillab/reader-api

jobs:
  include:
  - stage: test
    install:
    - yarn
    script:
    - yarn test
  - stage: build
    services:
    - docker
    install:
    - yarn
    script:
    - yarn build
    - docker build -t "$DOCKER_REPO" .
    - if [ ! -z "$TRAVIS_TAG" ]; then docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      for TAG in {"$TRAVIS_TAG",latest}; do docker tag "$DOCKER_REPO" "$DOCKER_REPO":"$TAG";
      docker push "$DOCKER_REPO":"$TAG"; done fi

cache:
  yarn: true
  directories:
  - node_modules

notifications:
  email: false
  slack:
    secure: vx2lx814br9ZtInNa13mff1ohrz1rb935dK55FZxelV9ebqCESyfd66q6u9iijGwALDJXVCbhs3TctVI+Gmvu3U7gaRxtLHjErgXsJVdEXb6ya0J6cTrrVEi/V0Euq87kbX1Qd8RvnCZO5YQLn2oG/517Ywu2IaIE7YkPpWKOJqn/DprqoZ1F6s+0Lhrnvx2IaS2qXRMl1yK8DhdmKuY2FqkCQibUjCJGcZvY6/PYVS95TPCuQLefu6SJn0lnsKI4M0YBhOa4kMFxTX31aoSGhX1AyCoEJwJSs/FCHRY8UsvccQYtXNiaiHz+IJp85m1O1jCm2Dn+xgwNETi8hQxjB1zYIduCk5OEk1GxMaPgip8/5WLNc7kl9wi6Kyt92SyLScrJQ0I9vD8KcJy2YQxjYtqiD/opFiSWQPXMwqa+Ngl0EdpTez55fqDMehyuV+GWngjhx4hE4fDAZlvGRjNPNBlS43Y4usgEDDtaqbQNPmJnSZtonyNluoq7M+UlZAJq+6q/V6Mb6qzGvsLFe1P1VtPygeFuRN28Dp3/ZH+aP4Itooy86OfidthBRnkxo9DGO7OvpcNNBVuPbJhQadMljTH7Lc9Y/UvwK4R4HXdFvN7jcPRkeP2aOh1m2fc2uFUsW7UTu3zo0YiX7Z3P//eAWoFMldFsCKsIPMMvBf5I8U=
