swagger: "2.0"
info:
  description: "reader api service"
  version: "0.0.1"
  title: "Reader API"
  contact:
    email: "hello@gorillab.co"
host: "glab-reader-api.herokuapp.com"
basePath: "/api"
tags:
- name: "auth"
  description: "Auth module"
- name: "user"
  description: "User module"
- name: "source"
  description: "Source module"
- name: "post"
  description: "Post module"
schemes:
- "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /auth/facebook:
    get:
      tags:
      - "auth"
      summary: "Logs user into the system by facebook"
      description: ""
      operationId: ""
      responses:
        200:
          description: "successful operation, send a facebook login form"
  /auth/facebook/callback:
    get:
      tags:
      - "auth"
      summary: "Facebook call this api to return result of authentication"
      description: ""
      operationId: ""
      responses:
        200:
          description: "successful operation"
  /auth/logout:
    get:
      tags:
      - "auth"
      summary: "Logs out current logged in user session"
      description: ""
      operationId: "logout"
      parameters: []
      responses:
        default:
          description: "successful operation"
  /user/subscriptions:
    get:
      tags:
      - "user"
      summary: "Returns all sources of user available in the database"
      description: ""
      operationId: "getUserSource"
      parameters:
      - name: "sort"
        in: "query"
        description: "Sort the list of sources by property"
        required: false
        type: "string"
      - name: "limit"
        in: "query"
        description: "Limit number of sources return from server"
        required: false
        type: "string"
      - name: "page"
        in: "query"
        description: "How many rows to skip"
        required: false
        type: "string"
      - name: "query"
        in: "query"
        description: "Keywords to search"
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Source"
      security:
      - UserSecurity: []
  /user/saved:
    get:
      tags:
      - "user"
      summary: "Returns all saved post of user available in the database"
      description: ""
      operationId: "getUserSavedPost"
      parameters:
      - name: "sort"
        in: "query"
        description: "Sort the list of posts by property"
        required: false
        type: "string"
        enum:
          - "new"
          - "best"
          - "daily"
      - name: "limit"
        in: "query"
        description: "Limit number of posts return from server"
        required: false
        type: "string"
      - name: "page"
        in: "query"
        description: "How many rows to skip"
        required: false
        type: "string"
      - name: "query"
        in: "query"
        description: "Keywords to search"
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Post"
      security:
      - UserSecurity: []
  /sources:
    get:
      tags:
      - "sources"
      summary: "Returns all sources available in the database"
      description: ""
      operationId: "allSource"
      parameters:
      - name: "sort"
        in: "query"
        description: "Sort the list of sources by property"
        required: false
        type: "string"
      - name: "limit"
        in: "query"
        description: "Limit number of sources return from server"
        required: false
        type: "string"
      - name: "page"
        in: "query"
        description: "How many rows to skip"
        required: false
        type: "string"
      - name: "query"
        in: "query"
        description: "Keywords to search"
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Source"
  /sources/{id}/subscriptions:
    put:
      tags:
      - "sources"
      summary: "Subscribe a source"
      description: ""
      operationId: "subscribeSource"
      parameters:
      - name: "id"
        in: "path"
        description: "Source id to subscibe"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Source"
        404:
          description: "Source not found"
      security:
      - UserSecurity: []
    delete:
      tags:
      - "sources"
      summary: "Unsubscribe a source"
      description: ""
      operationId: "unSubscribe"
      parameters:
      - name: "id"
        in: "path"
        description: "id of the source to delete"
        required: true
        type: "string"
      responses:
        200:
          description: "Source unsubscribed"
        404:
          description: "Source not found"
      security:
      - UserSecurity: []
  /posts:
    get:
      tags:
      - "posts"
      summary: "Returns all posts available in the database"
      description: ""
      operationId: "allPost"
      parameters:
      - name: "sort"
        in: "query"
        description: "Sort the list of posts by property"
        required: false
        type: "string"
        enum:
          - "new"
          - "best"
          - "daily"
      - name: "limit"
        in: "query"
        description: "Limit number of posts return from server"
        required: false
        type: "string"
      - name: "page"
        in: "query"
        description: "How many rows to skip"
        required: false
        type: "string"
      - name: "query"
        in: "query"
        description: "Keywords to search"
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Post"
  /posts/{id}/{action}:
    put:
      tags:
      - "posts"
      summary: "Action for post"
      description: ""
      operationId: "actionPost"
      parameters:
      - name: "id"
        in: "path"
        description: "Post id to view/save/share"
        required: true
        type: "string"
      - name: "action"
        in: "path"
        description: "Post id to view/save/share"
        required: true
        type: "string"
        enum:
          - "new"
          - "best"
          - "daily"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Post"
        404:
          description: "Post not found"
      security:
      - UserSecurity: []

securityDefinitions:
  UserSecurity:
    type: basic

definitions:
  User:
    type: "object"
    required:
    - "email"
    properties:
      id:
        type: "string"
        description: "Id for the user"
      email:
        type: "string"
        description: "Email for the user"
      token:
        type: "string"
        description: "Token for the user when login by email"
      vendor:
        type: "string"
        description: "Vendro for the auth"
      sources:
        type: "array"
        items:
          type: "string"
          description: "Reference to source model"
      profile:
        type: "object"
        properties:
          id:
            type: "string"
            description: "Facebook id"
          username:
            type: "string"
            description: "Facebook username"
          displayName:
            type: "string"
            description: "Facebook display name"
          name:
            type: "object"
            properties:
              familyName:
                type: "string"
                description: "Facebook first name"
              giveName:
                type: "string"
                description: "Facebook last name"
              middleName:
                type: "string"
                description: "Facebook middle name"
          gender:
            type: "string"
            description: "Facebook gender"
          profileUrl:
            type: "string"
            description: "Facebook profile url"
          emails:
            type: "array"
            description: "Facebook email list"
            items:
              type: "string"
          photos:
            type: "array"
            description: "Facebook photo list"
            items:
              type: "string"
  Source:
    type: "object"
    required:
    - "title"
    - "url"
    properties:
      id:
        type: "string"
        description: "Id for the source"
      title:
        type: "string"
        description: "Title for the source"
      url:
        type: "string"
        description: "Url for the source"
  Post:
    type: "object"
    required:
      - "title"
      - "url"
    properties:
      id:
        type: "string"
        description: "Id for the post"
      title:
        type: "string"
        description: "Title for the post"
      content:
        type: "string"
        description: "Content for the post"
      image:
        type: "string"
        description: "Image path for the post"
      url:
        type: "string"
        description: "Url for the post"
      source:
        type: "string"
        format: "objectId"
        description: "Reference to Source model"
      meta:
        type: "object"
        description: "Meta of the post"
        properties:
          numViewed:
            type: "integer"
            format: "int64"
            description: "Count number of views in the post"
          numShared:
            type: "integer"
            format: "int64"
            description: "Count number of shares in the post"
          numSaved:
            type: "integer"
            format: "int64"
            description: "Count number of saves in the post"
